<template>
  <div class="settings-page"><div class="mb-8 flex flex-col gap-4 border-b border-gray-200 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-2xl font-bold text-gray-900">Tipos de documentos</h1><p class="mt-2 text-sm text-gray-500">Cadastre os nomes disponíveis no envio de documentos dos negócios.</p></div><button class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white" @click="open = true">+ Novo tipo</button></div>
    <div class="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><p v-if="loading" class="p-8 text-center text-sm text-gray-500">Carregando...</p><p v-else-if="!documentTypes.length" class="p-8 text-center text-sm text-gray-500">Nenhum tipo de documento cadastrado.</p><ul v-else class="divide-y divide-gray-100"><li v-for="item in documentTypes" :key="item.id" class="flex items-center justify-between p-4"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 dark:bg-indigo-950/30"><Icon name="lucide:file-text" /></span><span class="text-sm font-semibold text-gray-900">{{ item.name }}</span></div><button class="rounded-md p-2 text-gray-400 hover:bg-red-50 hover:text-red-600" @click="remove(item.id)"><Icon name="lucide:trash-2" /></button></li></ul></div>
    <div v-if="open" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form class="w-full max-w-md space-y-4 rounded-xl bg-white p-6 shadow-xl dark:bg-slate-900" @submit.prevent="save"><h2 class="text-lg font-semibold">Novo tipo de documento</h2><label class="block space-y-2"><span class="text-xs font-semibold">Nome</span><input v-model.trim="name" required maxlength="100" class="w-full rounded-lg border px-3 py-2 dark:bg-slate-950" placeholder="Ex.: Comprovante de residência" /></label><div class="flex justify-end gap-2"><button type="button" class="rounded-lg border px-4 py-2 text-sm" @click="open = false">Cancelar</button><button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Salvar</button></div></form></div>
  </div>
</template>
<script setup lang="ts">
const toast = useToast(); const { documentTypes, loading, loadDocumentTypes, addDocumentType, removeDocumentType } = useDocumentTypes(); const open = ref(false); const name = ref('');
const save = async () => { await addDocumentType(name.value); name.value = ''; open.value = false; toast.success('Tipo de documento criado.') }
const remove = async (id: number) => { if (await toast.confirm('O tipo será excluído.', { title: 'Excluir tipo?', confirmLabel: 'Excluir' })) await removeDocumentType(id) }
onMounted(loadDocumentTypes)
</script>
